apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: default
spec:
  containers:
    - name: sample-container
      imagePullPolicy: Never
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
    - name: sample-container-2
      imagePullPolicy: Always
      command:
      - sleep
      - "3600"
      image: busybox
      ports:
        - containerPort: 80
          name: "http-server"
      
