apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-rs
  labels:
    app: my-app
spec:
  # modify replicas according to your use case
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: sample-nginx
        image: nginx
