apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  volumes:
    - name: sample-storage
      persistentVolumeClaim:
        claimName: sample-claim
  containers:
    - name: sample-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: sample-storage
