apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-volume
  labels:
    type: niranjan-label
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mydata"
